### ISSUE TITLE
Fix contracts information when they're deployed by another contract

### ISSUE THREAD

**Issue by ICONationDevTeam** [sudoblockio/icon-transformer#50]
Contracts deployed from another SCORE aren't displayed correctly in the tracker:

https://tracker.berlin.icon.community/contract/cx0b1e89cfa562721fbb7fcfe84acef604412fcba9#code

The ABI isn't displayed correctly:

![image](https://user-images.githubusercontent.com/69157597/195706754-dc8753c1-b43b-486f-80fa-360578ab6927.png)

The "Read Contract" tab fails with a "u.sent is undefined" error:

![image](https://user-images.githubusercontent.com/69157597/195706867-75e34a93-ed54-4121-8877-fd65a80c087c.png)

If needed, here's a  transaction leading to another contract creation : 

https://tracker.berlin.icon.community/transaction/0xd2d57a5b4623c53402c0050270f52b32d5576dabb3af6a614b7348fc174ca4e7

**Comment by robcxyz** [comment]
Links no longer work but I believe this is fixed.

**Comment by robcxyz** [comment]
Links no longer work but I believe this is fixed.
